alertmanager:
  enabled: false

pushgateway:
  enabled: false

server:
  service:
    type: NodePort
  persistentVolume:
    enabled: false

nodeExporter:
  enabled: false

kubeStateMetrics:
  enabled: false

kubelet:
  enabled: false

kubeProxy:
  enabled: false
