apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: pi-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ahmedfatnassi2/pi-frontend:latest
        ports:
        - containerPort: 5173
        env:
        - name: VITE_API_URL
          value: "http://backend-service:3001"
        livenessProbe:
          httpGet:
            path: /
            port: 5173
          initialDelaySeconds: 30
          periodSeconds: 10
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: pi-app
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 5173
  type: NodePort